ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Destila.Repo, :manual)
Supervisor.start_link([ClaudeCode.Test], strategy: :one_for_one)
Mimic.copy(Destila.Deps)
Mimic.copy(Destila.Git)
Mimic.copy(Destila.Projects)
Mimic.copy(Destila.Services.ProjectServices)
Mimic.copy(Destila.Services.ServiceManager)
Mimic.copy(Destila.Terminal.Tmux)
Mimic.copy(Destila.Terminal.PTY)
Mimic.copy(Destila.AI.AuthLogin)
Mimic.copy(Destila.Sessions.SessionProcess)
Mimic.copy(Destila.Proxy.Caddy)
Mimic.copy(ExPTY)
Mimic.copy(System)
Mimic.copy(Destila.Agent.EmbeddedHost)
Mimic.copy(Destila.Terminal.Server)
